// Code generated by "stringer -type ErrorCode"; DO NOT EDIT.

package cc111x

import "strconv"

const (
	_ErrorCode_name_0 = "ErrorRXTimeout"
	_ErrorCode_name_1 = "ErrorCmdInterrupted"
	_ErrorCode_name_2 = "ErrorZeroData"
)

var (
	_ErrorCode_index_0 = [...]uint8{0, 14}
	_ErrorCode_index_1 = [...]uint8{0, 19}
	_ErrorCode_index_2 = [...]uint8{0, 13}
)

func (i ErrorCode) String() string {
	switch {
	case i == 170:
		return _ErrorCode_name_0
	case i == 187:
		return _ErrorCode_name_1
	case i == 204:
		return _ErrorCode_name_2
	default:
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
